name: mela
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
   # A
  another_flushbar: ^1.12.29
  # B
  # C
  cupertino_icons: ^1.0.5
  # D
  dio: ^5.1.1
  # E
  event_bus: ^2.0.0
  # F
  flutter_mobx: ^2.0.6+5
  flutter_countdown_timer: ^4.1.0
  # G
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  # H
  http: ^0.13.5
  # I
  intl: ^0.19.0
  # J
  json_serializable: ^6.6.1
  # K
  # L
  # M
  mobx: ^2.1.4
  # N
  # O
  # P
  path_provider: ^2.0.14
  # Q
  # R
  # S
  shared_preferences: ^2.1.0
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  # T
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  # Y
  # Z


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/topics/
    - assets/icons/
    - assets/icons/arrow_back_longer.png
    - assets/icons/clock.png
    - assets/icons/select_list.png

    - assets/images/exit_image.png
    - assets/images/result_image.png
    - assets/lang/
  fonts:
  - family: Asap
    fonts:
      - asset:   assets/fonts/Asap/Asap-Regular.ttf
      - asset:   assets/fonts/Asap/Asap-SemiBold.ttf
      - asset:   assets/fonts/Asap/Asap-Bold.ttf
      - asset:   assets/fonts/Asap/Asap-ExtraBold.ttf

  - family: Mulish
    fonts:
      - asset: assets/fonts/Mulish/Mulish-Bold.ttf
      - asset: assets/fonts/Mulish/Mulish-Regular.ttf
      - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
      - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
